### ISSUE TITLE
[MyMeta] Editing skills doesn't appear to save changes, but actually does

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#363] opened 2021-02-25 20:39 UTC
If you e.g. add a skill and click the next button, then go back, the skill you just added is not there. Nor will it appear on your player card on the home page. Refreshing the page re-fetches the data and the next skill does show up.

Thus, skill changes are persisted to the database but not to the app state.

**Comment by dan13ram** [comment] 2021-02-26 11:50
Data not appearing on the player card would just be a delay due to NextJS SSG. But the other issue does need fixing.

**Comment by alalonde** [comment] 2021-08-29 19:02
The issue is not that the skills don't save, it's that they don't _appear_ to save if you e.g. change your skills, click save, and then click the left arrow on the progress bar to go back to skills.

**Comment by leewardbound** [comment] 2021-08-29 22:20
@alalonde thank you for clarifying! I didn't understand I had to click the back button, I thought original ticket meant "and then go back [to the players page]" -- I have reproduced this on my local, I will try to look into it this week!

**Comment by leewardbound** [comment] 2021-09-01 18:14
Worked on this today with @mquellhorst -- we tracked down the bug for an hour, identified the exact source of the problem (the "getMeQuery" is re-running on every form submission, except for this page, and we don't know why), and were unable to deduce a proper solution --

However, as this whole flow is going to be replaced by the new Edit Profile flow -- See #278  -- it seems it's not worth the effort to fix this on a page that will soon be phased out. Instead, I'm starting work on the frontend for the new unified Edit Profile page. Michiel has requested I close this ticket as "wont fix", thanks for the report!

**Comment by alalonde** [comment] 2021-09-29 04:04
Tracked this one down while working on #311, it's due to the `getMe` query being cached and re-used rather than fetched every time (https://formidable.com/open-source/urql/docs/basics/document-caching/). Will be fixed shortly

**Closed** 2022-10-12 09:35 UTC
Labels: bug, good 1ˢᵗ issue, frontend
