### ISSUE TITLE
BrightID Verification not working

### ISSUE THREAD

**Issue by Baconaetor** [MetaFam/TheGame#1152] opened 2022-02-18 17:39 UTC
### What happened?

I've never been able to verify my MyMeta profile with BrightID. The QR code doesn't scan, and opening the link in the app doesn't scan. A new member in Discord also had an issue where they received an error message. 
https://discordapp.com/channels/629411177947987986/713513935789097102/916324350637002792

### What did you expect to happen?

Not sure what the expected behavior is exactly. 

### How can we reproduce the problem (as minimally as possible)?

Problem can be reproduced by attempting to verify against the respective profiles. 

### Browser and operating system used (if applicable)

I used Firefox on desktop, and MetaMask browser on mobile.

**Comment by alalonde** [comment] 2022-02-18 20:35
This is a dupe of #1068

**Closed by alalonde** 2022-02-18 20:35 UTC
Labels: bug

**Comment by Baconaetor** [comment] 2022-02-18 20:45
> This is a dupe of #1068

Ugh, the GitHub search sucks apparently.
