### ISSUE TITLE
[MyMeta] Add filters to /players page

### ISSUE THREAD

**Issue by dan13ram** [MetaFam/TheGame#503] opened 2021-05-04 13:04 UTC
Right now, there is only a list of players.
If we want to make the player explorer more useful, we should allow people to search & filter it.

A player should be able to search the player list, filter it skills & availability at the very least.

The design:
![image](https://user-images.githubusercontent.com/55857222/117818045-7f7a5a80-b268-11eb-8bde-6a02595ff6aa.png)
[Figma file](https://www.figma.com/file/zDHqledo5H2aKR3KDvbur8/Meta-Game?node-id=3110%3A4014)

**Comment by davort** [comment] 2021-05-17 21:29
**Early feedback**
Solid implementation, however not following Figma in its entirety. 
I have also updated the Figma file slightly, so as to make UI clearer: [Figma link](https://www.figma.com/file/zDHqledo5H2aKR3KDvbur8/Meta-Game?node-id=3110%3A7234)

I'd appreciate if you could do the following:
1. Add background color to dropdowns, as defined in Figma (#1B0D2A)
2. Use those down-pointed arrows for the dropdowns. I've made them exportable now. -- _This is optional. If it's too much work, feel free to leave it as is._
3. Use the same border style for dropdown buttons as is defined in Figma (2px, solid, #5946BC).
4. Make the search field a rectangle, with border-radius: 0 -- _This is to differentiate the search field from dropdowns._
5. Make the placeholder text semi-transparent (opacity: 50%)
6. I tried entering a search phrase and hitting "enter", but that didn't seem to work. Can we make it work like that? -- _This is important._

Let me know if you have any thoughts, comments, or when you'd like me to take another look.
Thanks in advance!

**Comment by peth-yursick** [comment] 2021-05-18 10:45
Just pasting over from Discord:

We should probably add more times between 0 & >10h. Maybe 1h & 5h? But that's probably a separate issue.
Also, we dropped "pioneers, settlers & town planners" meanwhile for the MTG colors, so that would be more important to put on.
What is the difference between "dev" & "engineering"? Would it make more sense to merge along with "technologies" since it doesn't allow picking the subset of technologies anyway?

As for the design itself, wait for @Davor 🐙's opinion because I'm not a designer but it might be good to match these, to make the panel transparent like the cards & the buttons without the borders. Could also make the dropdown itself round cornered bottom & semi transparent.
![image](https://user-images.githubusercontent.com/55857222/118638172-d76c1080-b7d6-11eb-9fae-910de2dfc282.png)

**Comment by dan13ram** [comment] 2021-05-18 11:09
@peth-yursick 
> What is the difference between "dev" & "engineering"? Would it make more sense to merge along with "technologies" since it doesn't allow picking the subset of technologies anyway?

These categories are subcategories of skills in https://my.metagame.wtf/profile/setup/skills
So technologies/dev/engineering are all different. 

I totally get that it can be confusing. I can change this to show all skills if you that would be better.

**Comment by dan13ram** [comment] 2021-05-18 12:27
@peth-yursick Regarding the ColorAspects, these are the different options available as per the database
```
ColorAspects = [
  "Colorless",
  "Authenticity",
  "Profanity",
  "Independence",
  "Realism",
  "Truth-Seeking",
  "Creativity",
  "Savagery",
  "Growth Mindset",
  "Ruthlessness",
  "Iconoclasm",
  "Turmoil",
  "Community",
  "Heroism",
  "Contentment",
  "Tribalism",
  "Endurance",
  "Speed",
  "Aggression",
  "Structure",
  "Complacence",
  "Cunning",
  "Altruism",
  "Dedication",
  "Growth",
  "Artifice",
  "Wholeness",
  "Balance",
  "Justice",
  "Wisdom",
  "Ambition",
  "Chaos"
]
```

We can create a filter based on these. But imo these are not easy to understand. 
But this can be done. Let me know :)

**Comment by dan13ram** [comment] 2021-05-18 12:28
@davort I've updated the PR with yours as well as @peth-yursick 's suggestions. 
Please take a look and let me know what you think :)
https://the-game-git-feat-filters-metafam.vercel.app/players

**Comment by davort** [comment] 2021-05-18 14:28
@dan13ram – you're welcome! Thank you for doing a great job taking care of that first round of feedback. I have another few questions and comments:

**1. The first dropdown—number of results to display—isn't in the design mockup.** What is the use case where _anyone_ would be interested in fiddling with this? Why not just show the maximum that is technically feasible, and if it doesn't fit onto a single page, that can be fixed with pagination. Also, this looks funny (screenshot) 
![filters-ant](https://user-images.githubusercontent.com/1573304/118668621-55d7ab00-b7f5-11eb-9cdf-8364a979440f.png)

**2. Number of results is formatted differently than in the design mockup.** Would be better to implement it as it was suggested in the design mockup, because people scan pages in the so-called "F pattern". Hence, better to have that info aligned to the left of the page.

**3. Instead of "number of results", a "Sort by" dropdown might actually be useful.** What is the default sort criteria? Happy to hear your thoughts on this one.

**4.** When the user makes selections in more than one of the filter dropdowns, **it might be nice to offer a "RESET ALL FILTERS" button.** Let me know what you think about that.

**Comment by dan13ram** [comment] 2021-05-19 09:37
Thanks @davort .

1 & 2. I consciously moved away from the design and added the "first dropdown" as well as moved the "number of results" to the top right. This was in order to keep the same design across different pages. Please see below the current screenshot of `/quests` page
![Screenshot from 2021-05-19 15:04:29](https://user-images.githubusercontent.com/10012209/118790584-89790a80-b8b3-11eb-8edd-26b325d7adfb.png)
Having shared that, I'm definitely in favor of the figma + some pagination. 
Would you be kind enough to share some design mockups for how pagination might look?
3. Its currently sorted by descending order of `total xp`. Can certainly add an option to do ascending order if thats something we want.
4. Please share a design mockup for this "Reset All Filters" option  as well. 🙏

**Comment by dan13ram** [comment] 2021-05-19 15:16
Sharing some suggestions from Hammad here:

> Also feel like the UX might be better if it was a floating sidebar on desktop and a collapsible section on mobile.
> Also would be nice to be able to filter by DAO membership, could replace timezone for that.

**Comment by davort** [comment] 2021-05-20 08:19
Thanks for bringing more clarity around 1 & 2 @dan13ram 👍 
I appreciate your caring about keeping things consistent. You have goods instinct, so props for that. The problem is at the design level, so thanks for letting me know about this. Not a big issue, but also very easy to fix, so we'll do that!

3. XP "descending" (default) and "ascending" sounds like a good starting point.
4. I will make some adjustments to the mockup, and then share it with you.

**Comment by davort** [comment] 2021-05-20 08:22
Also @dan13ram thanks for passing forward Hammad's suggestions!

If I'm interpreting his thinking correctly, and try to express it as a "job story", it might look something like this
> When **I scroll through the results**, I want to **be able to adjust my filter selections on the fly** so that I can **be more efficient when searching**.

or

>When **I scroll through the results**, I want to **see what filters are currently active**, so that I **can mentally connect the input and the output of the search criteria**.

This way, we can focus on desired outcomes, instead of solutions—_WHY?_  instead of  _WHAT?_—and proceed to find an optimal solution, considering the larger context, which this particular UI is a small part of.

It's very valuable, and I agree with this idea, so let me come back with a proposal that will hopefully be technically feasible, as well as usable!

**Comment by davort** [comment] 2021-05-20 09:39
Lastly, my 2 cents on the "Time zone" option for filtering. What's there currently ended up being one super-long list of options. Not very usable in terms of design, but perhaps neither as a concept. 

When talking time zones, rather being able to find people in one select zone, it's much more likely we are thinking of **overlap**, which ends up being a range, instead of one exact value. The idea being "I'm looking for people I'd like to work with, so it's important that we can easily touch base any day, at least during a set time window."

That said, "my time zone, or any of the adjacent ones, that might span +/- 4 hours from the one I'm in" might be a more convenient mental model.

By sharing this, I don't mean to suggest huge additions or extensions of the UI you are currently building, @dan13ram 
Instead, I'd like to hear your thoughts around it, first. In case you think this is something that might be interesting and useful to have for users, we might wanna create a separate issue for this and tackle it there.

**Comment by peth-yursick** [comment] 2021-06-04 12:07
> 
> 
> @peth-yursick Regarding the ColorAspects, these are the different options available as per the database
> 
> ```
> ColorAspects = [
>   "Colorless",
>   "Authenticity",
>   "Profanity",
>   "Independence",
>   "Realism",
>   "Truth-Seeking",
>   "Creativity",
>   "Savagery",
>   "Growth Mindset",
>   "Ruthlessness",
>   "Iconoclasm",
>   "Turmoil",
>   "Community",
>   "Heroism",
>   "Contentment",
>   "Tribalism",
>   "Endurance",
>   "Speed",
>   "Aggression",
>   "Structure",
>   "Complacence",
>   "Cunning",
>   "Altruism",
>   "Dedication",
>   "Growth",
>   "Artifice",
>   "Wholeness",
>   "Balance",
>   "Justice",
>   "Wisdom",
>   "Ambition",
>   "Chaos"
> ]
> ```
> 
> We can create a filter based on these. But imo these are not easy to understand.
> But this can be done. Let me know :)

Is there no such thing as just "colors" & only "color aspects"?
The actual colors are supposed to be just White, Red, Green, Blue & Black..

**Comment by dan13ram** [comment] 2021-06-04 12:08
Sorry for the delay in response @davort. But yes, definitely a better timezone filter would be very useful.
I see on the figma that you're already working on creating one, looking forward to seeing the result of that :)

**Comment by dan13ram** [comment] 2021-06-04 12:13
> Is there no such thing as just "colors" & only "color aspects"?
> The actual colors are supposed to be just White, Red, Green, Blue & Black..

@peth-yursick  this is how its stored in the db, and there is some frontend logic to convert these labels to visualise as colors.
We could build a filter that shows the colors, and recreate those labels from the filter. But I will need to dig deeper into how the colors and labels are linked for that.
Thats as much as I understand it, maybe @dysbulic can share some more light on this.

**Comment by dysbulic** [comment] 2021-06-04 12:52
The color names came from three places: the base color names were part of the [original design](https://discord.com/channels/629411177947987986/782054676546846752/812437464663851048), the three color combinations are pulled from [the long color article](https://humanparts.medium.com/the-mtg-color-wheel-c9700a7cf36d), & the rest I made up based on the descriptions to avoid any potential legal issues with Wizards of the Coast.

The storage is the database is based on a five-element bitfield. WBUGR, so pure red would be `0b00001 = 1` & pure white `0b10000 = 16`.

The interface I'd go with is a set of checkboxes by each of the colors and filter using that. I'd not worry about the names at all b/c they really don't clarify anything.

**Comment by davort** [comment] 2021-06-10 20:05
@dan13ram – An idea, **re: sorting the list.**

Sort by:
1. Most XP (default)
2. Nearest to me / time-zone difference
3. Most Availability
4. Name (A – Z)
5. Name (Z – A)

Let me know your thoughts!

**Comment by dan13ram** [comment] 2021-06-11 02:14
@davort these are my thoughts:
4. and 5. Sorting by name is not possible. But if we can tweak that to sort by username then it should be possible.
1. and 3. Can be done in a straightforward manner.
2. This also seems impossible to me right now because of the way the timezone is stored in our database. But I think we might be able to accomplish it with a bunch of effort on the backend and the frontend.

**Comment by davort** [comment] 2021-06-11 06:40
@dan13ram
1) 3) - great!
2) I understand. Might it be easier once the database is restructured - or remapped - to show countries and continents? Please give it a thought and let me know.
4) 5) - that's what I was thinking, username! ☺️

Cool, so it's 4 out of 5, from the start!

**Comment by davort** [comment] 2021-06-13 08:17
@dan13ram please find the first stab at the mobile version of the Filters UI, here: https://www.figma.com/proto/zDHqledo5H2aKR3KDvbur8/Meta-Game?page-id=5763%3A9&node-id=6974%3A14&viewport=1831%2C-2241%2C0.7867474555969238&scaling=min-zoom

Let me know what you think. Is anything missing? Will anything be hard to implement? Feel free to ignore the "push" effect when moving through the filter panels, if that could be an issue for whatever reason.

Figma mockups, for inspection of properties and exporting assets (icons) is here: https://www.figma.com/file/zDHqledo5H2aKR3KDvbur8/Meta-Game?node-id=6974%3A14

**Comment by mquellhorst** [comment] 2021-07-06 19:36
During the latest DAO call a discussion came up about viewing the players by the XP earned during the current season.
I proposed building an extra filter which sorts the player list by the XP earned in the current season.

So this would add an extra option in the filters to sort the players by:
- Total XP
- Seasonal XP

Since you're (@dan13ram) are working on this issue, could you implement this as well or would you rather have me create a seperate issue for this?

**Comment by davort** [comment] 2021-07-06 20:38
@mquellhorst — I thought that was a great idea! 
I'd suggest to have the "Most XP this season" selected as the default sorting parameter, so that the page shows who are currently the most engaged players already on the initial load. Then have "Most XP all time" added as a nice additional sorting option.

@dan13ram — if you agree, let's please have the "Sort by" dropdown have the following options:

- XP this season (default)
- XP all time
- Most Availability
- Name (A → Z)
- Name (Z → A)

**Comment by dan13ram** [comment] 2021-07-07 05:35
Thanks @davort  and @mquellhorst. We can definitely do this, how do we define a season currently.
Can someone help me with the correct time periods for each season ?

**Comment by davort** [comment] 2021-07-07 08:43
Yes @dan13ram – according to [Seasons & Phases (MetaGame Wiki)](https://wiki.metagame.wtf/docs/resources/glossary#season--phases) 

> Seasons revolve around shorter term goals & achievements, divided by actual seasons; spring, summer, autumn & winter.

When it comes to the actual dates, this might be a good reference: https://www.timeanddate.com/calendar/seasons.html → what do you say, @peth-yursick ?

**Comment by davort** [comment] 2021-07-09 19:21
**Time zone filter update**
@dan13ram managed to implement a script which allows for searching by city/state/country/continent directly in the time zone dropdown. 
![CleanShot 2021-07-09 at 21 13 58-1](https://user-images.githubusercontent.com/1573304/125126185-ff9f2e00-e0fa-11eb-96cd-15a65c72e892.gif)

We discussed ways of making it even more user-friendly, and I suggested that we go along with loading the list of search results, per user's filter selections, but then extend it with a list of "players from adjacent time zones", like this:
![expanded-timezones](https://user-images.githubusercontent.com/1573304/125126293-28272800-e0fb-11eb-96dd-af5b0e34366d.png)

We have made 3 decisions:
1) How much overlap? We'll go with +/- 4 hrs.
2) How to sort? from smaller overlap to bigger overlap. Start with offsets "before" mine/selected, to time zones "behind".
3) Change the time zone selection to single choice. Just so we keep this contained and understandable.

@dan13ram will be working on getting this done over the next couple of days. Once done, this should significantly increase the overall usefulness of the UI, while at the same time not requiring any additional effort from the user.

**Closed** 2021-08-25 14:56 UTC
Labels: frontend, design needed
