### ISSUE TITLE
[MyMeta] Add filtering capability

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#542] opened 2021-05-11 12:53 UTC
Right now, there is only a list of players.
If we want to make the player explorer more useful, we should allow people to search & filter it.

A player should be able to search the player list, filter it skills & availability at the very least.

The design:
![image](https://user-images.githubusercontent.com/55857222/117818045-7f7a5a80-b268-11eb-8bde-6a02595ff6aa.png)
[Figma file](https://www.figma.com/file/zDHqledo5H2aKR3KDvbur8/Meta-Game?node-id=3110%3A4014)

**Comment by dan13ram** [comment] 2021-05-12 06:37
@peth-yursick duplicate of #503 ?

**Closed** 2021-05-17 13:04 UTC
