### ISSUE TITLE
Display boxes are cropped on player profile page

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1050] opened 2022-01-17 08:29 UTC
### What happened?

Currently the player's profile display page looks something like:

![screencapture-localhost-3000-player-dysb-2022-01-17-01_51_26](https://user-images.githubusercontent.com/181523/149721420-ca51b1ca-c8d6-407b-9985-75253977d008.png)

Several of the boxes (the primary profile info, player type, & top NFTs) are cropped at a height that doesn't allow the display of all the box's contents. Additionally, there are no scroll bars to allow accessing the information, but this is secondary because the information should simply all be displayed without requiring scrolling.

### What did you expect to happen?

Player profile information should be one, two, or three columns of boxes depending on screen width. The height of the boxes should be determined by their content.

Setting the `column-count` CSS property on the container, and `break-inside: avoid` on the content boxes should produce a roughly balanced columnated layout.

### How can we reproduce the problem (as minimally as possible)?

View [a player profile on the test server](https://test.metagame.wtf/player/dan13ram) and note that some of the boxes are truncated.

### Is there anything else we need to know?

One of the features that `react-grid-layout` provides the ability to dynamically reposition and resize the contents of columns.

While this is a handy feature, it is far less important than that the profile information be displayed as cleanly as possible.

In the short term box position editing could be disabled, and readded using a different interface later.

**Comment by vidvidvid** [comment] 2022-01-17 08:45
Duplicate of #1036 

The screenshots in #1036 are not up to date, but the problem is the same.

**Closed by vidvidvid** 2022-01-17 08:45 UTC
Labels: bug, frontend
