### ISSUE TITLE
[App Drawer] Mobile Issues

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#268] opened 2021-01-12 10:46 UTC
There are currently 4 known issues on the mobile app drawer:
~~- When loading MyMeta, the appdrawer quickly flashes as if its open then closes. It should be closed by default & not appearing in a flash like that.~~
~~- The buttons have no titles~~
~~- The crystal still has the blue frame thing~~
- The light blue app drawer background appears over a part of the navigation bar
~~- There is a blue frame around the logo button~~

**Comment by alalonde** [comment] 2021-01-14 00:24
#276 addresses the second item.

I couldn't reproduce the third and fourth items; are those still an issue? If so, on which device?

**Comment by peth-yursick** [comment] 2021-01-26 22:38
> I couldn't reproduce the third and fourth items; are those still an issue? If so, on which device?

Looks like the issue is only on mobile

**Comment by peth-yursick** [comment] 2021-01-27 15:43
Didn't realize this whole issue is just about mobile issues.. I'm on Android, Samsung.
Its the same problem both on latest Chrome & Firefox.

**Comment by peth-yursick** [comment] 2021-01-29 00:20
Maybe the latest version hasn't deployed yet or something, but on Android I'm still seeing all of the problems listed above except no.2 
@hammadj

**Comment by alalonde** [comment] 2021-01-29 02:42
Yeah I don't think anybody has worked on those other fixes yet.

**Comment by dysbulic** [comment] 2021-01-30 04:17
This will be resolved with the merge of #294.

**Comment by luxumbra** [comment] 2021-02-18 22:51
> The light blue app drawer background appears over a part of the navigation bar
there looks to be a z-index issue where the bottom 3 app drawer items sit above the MG crystal so the top half of the crystals active area links to the leaderboard.

**Closed** 2021-03-27 23:46 UTC
