### ISSUE TITLE
[MyMeta] Make the whole Player card clickable

### ISSUE THREAD

**Issue by markoprljic** [MetaFam/TheGame#343] opened 2021-02-12 16:14 UTC
On My Meta homepage make the whole player card clickable so that it is easier to access the player profile page.
Current behavior: Player name is a link (clickable)
New behavior: Player Card is a link (clickable)

**Comment by dysbulic** [comment] 2021-03-11 02:00
It turns out this is more difficult than it appears at first glance. The issue is the links to Twitter, Github, & Etherscan that can appear in the footer of the player card.

Wrapping the entire card in a link will override the destination of those links. There is a [CSS-based solution](https://stackoverflow.com/questions/9882916/are-you-allowed-to-nest-a-link-inside-of-a-link/46707009#46707009) that involves putting the card link as an absolutely positioned background behind the social media links (but not nesting them).

**Comment by sunguru98** [comment] 2021-03-26 16:24
I'll take this one and see if this is possible. @dysbulic @markoprljic

**Comment by luxumbra** [comment] 2021-06-07 00:45
How did you get on with this @sunguru98?

**Comment by dan13ram** [comment] 2021-06-07 00:54
Hey guys, I wonder if a simpler solution would be to change the href links to a button onClick and prevent event propogation for those links alone. But either works

**Comment by luxumbra** [comment] 2021-06-07 16:15
A simple abs pos link, like @dysbulic suggested, to fill the card behind the social links would be a pretty quick fix for this and I prefer it over using Buttons for navigational elements.

**Comment by jonathanprozzi** [comment] 2021-06-10 02:52
I was checking this out after seeing it on the call this morning and I'm playing around with it a bit. I'm going to try the abs pos link suggestion but I also have been looking into this with Chakra: https://chakra-ui.com/docs/navigation/link-overlay

Haven't used that component before but it looks like it preserves keyboard navigation. Trying this out as well.

**Comment by luxumbra** [comment] 2021-06-13 12:36
@jonathanprozzi if you are working on this, could you assign yourself (if you have the relevant permissions) and move into the 'in progress' pipeline? 🙏🏻

**Comment by sunguru98** [comment] 2021-06-14 04:01
Made some changes thats now supporting the whole player card as well as the name being clickable :)

**Comment by markoprljic** [comment] 2021-06-14 05:36
Woohoo!

**Comment by davort** [comment] 2021-06-23 16:25
Hi @sunguru98 – I just took [the current implementation](https://the-game-git-fork-sunguru98-feature-player-card-c3cbf1-metafam.vercel.app/players) for a spin. Unfortunately, there are still issues, as seen in the video capture, that can be seen in a video capture below:

1. The card isn't clickable in parts where some kind of text exists. It should all just be clickable, anywhere in the card, and open the profile page for the player whose card was clicked.
2. Can we please have some kind of a subtle :hover effect on the card's background, such as perhaps changing it to "rgba(255, 255, 255, 0.12)"? Just so there is more to indicate that the whole card is clickable, other than the mouse cursor change, which is easily overlooked.

https://user-images.githubusercontent.com/1573304/123132723-5516e200-d44f-11eb-8ff1-6c704de2e247.mp4

Thanks!

**Comment by sunguru98** [comment] 2021-06-23 22:54
Hey @davort, thanks for taking the time to review it. 
Regarding 1, if that needs to be solved, then the underlying links of Twitter and any redirecting URLs would also be affected by this click. Any suggestions you could provide to overcome this issue? I guess the reason why it can't be clickable in most of the regions is because the smaller badges/components present inside. 

Regarding 2, that can be done :)

**Comment by davort** [comment] 2021-06-24 04:27
@sunguru98 - you bring up a valid point with the underlying links issue 👍
1. Can we hide/remove the whole "Contact" section from the card? That would effectively remove the issue, and I bet nobody would even notice the section is gone from the card 😉 The section would, of course, stay there in the profile page, once it's opened.
2. Excellent! 👌

**Comment by luxumbra** [comment] 2021-07-10 21:31
Hey folks. @sunguru98 how is this progressing? Do you help with anything? I hope all is well. 🙏🏻

**Comment by dysbulic** [comment] 2021-07-11 09:55
> 1. Can we hide/remove the whole "Contact" section from the card?

@davort, I for one look at people's GitHub and Twitter accounts. I've also mass copied ETH addresses from that index when testing NFTs. I think 86ing the Contacts section is a pretty big change & not something we should do without dicussion.

@sunguru98, you should be using [Chakra UI's `LinkOverlay`](https://chakra-ui.com/docs/navigation/link-overlay). It is designed for exactly this problem.

**Comment by luxumbra** [comment] 2021-07-11 11:46
> > 1. Can we hide/remove the whole "Contact" section from the card?
> 
> @davort, I for one look at people's GitHub and Twitter accounts. I've also mass copied ETH addresses from that index when testing NFTs. I think 86ing the Contacts section is a pretty big change & not something we should do without dicussion.

I would say that the contact info is pretty important as it is one of the main things a profile is for, so people can check out your cred, your code and see what your twitter is like before considering working with you.

**Comment by davort** [comment] 2021-07-11 12:38
Hey @dysbulic and @luxumbra, thank you for your input! 👍

Sure thing, let's leave it where it is, as long as we can find a way for the items in there not to interfere with the whole card being "clickable", and upon being clicked anywhere in the card area, opening the player's profile page.

It seems @dysbulic has a solution on mind. Hope we can try it out soon.

**Comment by luxumbra** [comment] 2021-07-11 18:58
I used `LinkOverlay` quite recently for the embedded url work i am doing for #264 and it works lovely. 👍🏻

**Comment by tommymaher15** [comment] 2021-07-27 13:37
This issue still active? I could take a look

**Comment by luxumbra** [comment] 2021-07-27 16:47
> This issue still active? I could take a look

Go for it @tommymaher15! Just make sure to assign to yourself and move to 'in progress' when you start. 👍🏻

**Comment by tommymaher15** [comment] 2021-07-29 01:01
This is an interesting one! 

Just took a look at the `LinkOverlay` as @luxumbra  mentioned above!

**Comment by tommymaher15** [comment] 2021-07-29 23:02
It appears that this approach isn't as simple as I thought. Will keep digging into this. Would love to jump on a call sometime with someone and get a feel for how things are structured so I could get upto speed on things!

**Closed** 2021-08-01 03:14 UTC
Labels: good first issue
